# Auth Service chạy ở port 8081
server.port=8081
spring.application.name=auth-service

# Cấu hình kết nối SQL Server tới database clothing_auth_db
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=clothing_auth_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình JPA / Hibernate tự sinh bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect