server.port=8083
spring.application.name=order-service

# Kết nối database riêng biệt clothing_order_db trên SQL Server
spring.datasource.url=jdbc:sqlserver://sqlserver:1433;databaseName=clothing_order_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=YourStrong@Passw0rd
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate tự động đồng bộ bảng dữ liệu
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Mở cổng Actuator giám sát cho mọi dịch vụ công khai
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

# Cấu hình Circuit Breaker cho Product Client
resilience4j.circuitbreaker.instances.productServiceCB.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.productServiceCB.slidingWindowSize=4
resilience4j.circuitbreaker.instances.productServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productServiceCB.waitDurationInOpenState=10000