server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**

        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/v1/products/**

        - id: product-service-uploads
          uri: http://product-service:8082
          predicates:
            - Path=/uploads/**

        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/api/v1/orders/**

        - id: category-service
          uri: http://category-service:8084
          predicates:
            - Path=/api/v1/categories/**

        - id: discount-service
          uri: http://discount-service:8085
          predicates:
            - Path=/api/v1/discounts/**