server.port=8888
spring.application.name=config-server

# Kích hoạt chế độ native đọc cấu hình từ thư mục local
spring.profiles.active=native
# Đường dẫn trỏ tới thư mục chứa toàn bộ file properties tập trung (Long tự thay đổi theo máy mình nhé)
spring.cloud.config.server.native.search-locations=classpath:/shared-configs